# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---


- name: CIS | Ensure address space layout randomization (ASLR) is enabled
  become: true
  ansible.builtin.template:
    src: 'etc/sysctl.d/60-kernel.conf.j2'
    dest: '/etc/sysctl.d/60-kernel.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when:
    - ansible_os_family in ['Debian', 'RedHat']

